export const SITE_NAME = "FragmentTrails";

export const DEFAULT_TITLE =
  "FragmentTrails | Scholarship Interview & Candidate Evaluation Platform";

export const DEFAULT_DESCRIPTION =
  "Streamline scholarship interviews, candidate scoring, and evaluation workflows with FragmentTrails. Improve fairness, consistency, and decision-making using structured assessment tools for education institutions and scholarship programs.";

export const DEFAULT_KEYWORDS = [
  "scholarship tracking and review system",
  "scholarship management software",
  "scholarship application tracking",
  "scholarship review workflow",
  "scholarship committee management",
  "scholarship evaluation platform",
  "scholarship applicant review system",
  "scholarship administration software",
  "scholarship selection process",
  "higher education scholarship management",
  "scholarship review dashboard",
  "scholarship interview platform",
  "scholarship interview software",
  "scholarship assessment platform",
  "candidate evaluation software",
  "applicant scoring system",
  "scholarship selection software",
  "student interview platform",
  "admissions interview software",
  "interview evaluation platform",
  "interview moderation software",
  "bias free candidate evaluation",
  "structured interview assessment",
  "scholarship review process",
  "interview panel management",
  "education technology",
  "higher education",
  "scholarship programs",
  "admissions workflow",
  "AI moderation",
  "classroom discussion platform",
  "student engagement software",
  "educator recognition platform",
  "cohort based learning",
  "AI interview assistant",
  "automated interview scoring",
  "fair candidate assessment",
  "interview standardization",
  "panel calibration",
  "data driven selection",
  "scholarship committee tools",
  "academic interview management",
  "university admissions software",
  "college interview platform",
  "grant selection software",
  "fellowship interview tools",
  "education assessment platform",
  "learning management system",
  "online discussion platform",
  "student evaluation tools",
  "teacher recognition software",
  "FragmentTrails",
];

// Target countries for international SEO
export const TARGET_LOCALES = [
  { code: "en-US", name: "United States", priority: 1 },
  { code: "en-CA", name: "Canada", priority: 1 },
  { code: "en-GB", name: "United Kingdom", priority: 1 },
  { code: "en-AU", name: "Australia", priority: 1 },
  { code: "en-NZ", name: "New Zealand", priority: 1 },
  { code: "de-DE", name: "Germany", priority: 0.8 },
  { code: "nl-NL", name: "Netherlands", priority: 0.8 },
  { code: "sv-SE", name: "Sweden", priority: 0.8 },
  { code: "no-NO", name: "Norway", priority: 0.8 },
  { code: "fr-FR", name: "France", priority: 0.8 },
  { code: "en-SG", name: "Singapore", priority: 0.8 },
  { code: "en-PK", name: "Pakistan", priority: 0.6 },
  { code: "en-IN", name: "India", priority: 0.6 },
  { code: "en-AE", name: "UAE", priority: 0.6 },
];

// Content categories for silos
export const CONTENT_CATEGORIES = [
  {
    slug: "science",
    name: "Science",
    description: "Explore scientific discussions across physics, chemistry, biology, and more",
    keywords: ["science", "scientific", "research", "experiment", "hypothesis"],
  },
  {
    slug: "physics",
    name: "Physics",
    description: "Discuss mechanics, thermodynamics, quantum physics, and physical phenomena",
    keywords: ["physics", "mechanics", "quantum", "thermodynamics", "electricity"],
  },
  {
    slug: "chemistry",
    name: "Chemistry",
    description: "Explore organic chemistry, chemical reactions, molecular structures, and more",
    keywords: ["chemistry", "molecular", "organic", "reactions", "elements"],
  },
  {
    slug: "biology",
    name: "Biology",
    description: "Discuss genetics, ecology, evolution, microbiology, and life sciences",
    keywords: ["biology", "genetics", "ecology", "evolution", "microbiology"],
  },
  {
    slug: "mathematics",
    name: "Mathematics",
    description: "Explore algebra, calculus, statistics, and mathematical theories",
    keywords: ["mathematics", "algebra", "calculus", "statistics", "geometry"],
  },
  {
    slug: "computer-science",
    name: "Computer Science",
    description: "Discuss programming, algorithms, data structures, and software development",
    keywords: ["computer science", "programming", "algorithms", "software", "coding"],
  },
  {
    slug: "programming",
    name: "Programming",
    description: "Share code, discuss languages, and solve programming challenges",
    keywords: ["programming", "coding", "development", "software engineering", "web development"],
  },
  {
    slug: "artificial-intelligence",
    name: "Artificial Intelligence",
    description: "Explore machine learning, neural networks, and AI applications",
    keywords: ["artificial intelligence", "AI", "machine learning", "neural networks", "deep learning"],
  },
  {
    slug: "machine-learning",
    name: "Machine Learning",
    description: "Discuss ML algorithms, models, training, and data science applications",
    keywords: ["machine learning", "ML", "data science", "algorithms", "models"],
  },
  {
    slug: "data-science",
    name: "Data Science",
    description: "Explore data analysis, visualization, statistics, and big data",
    keywords: ["data science", "analytics", "visualization", "big data", "statistics"],
  },
  {
    slug: "engineering",
    name: "Engineering",
    description: "Discuss civil, mechanical, electrical, and software engineering topics",
    keywords: ["engineering", "civil", "mechanical", "electrical", "software engineering"],
  },
  {
    slug: "medicine",
    name: "Medicine",
    description: "Explore medical research, healthcare, and clinical discussions",
    keywords: ["medicine", "healthcare", "clinical", "medical research", "pharmacology"],
  },
  {
    slug: "history",
    name: "History",
    description: "Discuss historical events, civilizations, and historical analysis",
    keywords: ["history", "historical", "civilization", "archaeology", "historical analysis"],
  },
  {
    slug: "economics",
    name: "Economics",
    description: "Explore microeconomics, macroeconomics, and economic theory",
    keywords: ["economics", "microeconomics", "macroeconomics", "economic theory", "finance"],
  },
  {
    slug: "business",
    name: "Business",
    description: "Discuss entrepreneurship, management, marketing, and business strategy",
    keywords: ["business", "entrepreneurship", "management", "marketing", "strategy"],
  },
  {
    slug: "marketing",
    name: "Marketing",
    description: "Explore digital marketing, SEO, content marketing, and branding",
    keywords: ["marketing", "digital marketing", "SEO", "content marketing", "branding"],
  },
  {
    slug: "psychology",
    name: "Psychology",
    description: "Discuss cognitive psychology, behavioral science, and mental health",
    keywords: ["psychology", "cognitive", "behavioral", "mental health", "neuroscience"],
  },
  {
    slug: "education",
    name: "Education",
    description: "Explore teaching methods, educational technology, and learning theories",
    keywords: ["education", "teaching", "educational technology", "pedagogy", "learning"],
  },
  {
    slug: "research-methods",
    name: "Research Methods",
    description: "Discuss research design, methodology, and academic writing",
    keywords: ["research methods", "methodology", "research design", "academic writing", "statistics"],
  },
];
